trying something else

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -41,49 +41,32 @@ steps:
 #     python fusion_run -inputs ./data/unet.nii.gz,./data/resunet.nii.gz -output ./data/test_${{ method }}.nii.gz -classes 0,1,2,4 -method ${{ method }}
 #     python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_${{ method }}.nii.gz', './data/test_${{ method }}.nii.gz'))) else print('pass')"
 
-- bash: |
-    python fusion_run -inputs ./data/unet.nii.gz,./data/resunet.nii.gz -output ./data/test_staple.nii.gz -classes 0,1,2,4 -method staple 2> /dev/null 
-    if [ $? -eq 0 ]; then
-      exit 0
-    else
-      exit 1
-    python fusion_run -inputs ./data/unet.nii.gz,./data/resunet.nii.gz -output ./data/test_itkvoting.nii.gz -classes 0,1,2,4 -method itkvoting 2> /dev/null 
-    if [ $? -eq 0 ]; then
-      exit 0
-    else
-      exit 1
-    python fusion_run -inputs ./data/unet.nii.gz,./data/resunet.nii.gz -output ./data/test_majorityvoting.nii.gz -classes 0,1,2,4 -method majorityvoting 2> /dev/null 
-    if [ $? -eq 0 ]; then
-      exit 0
-    else
-      exit 1
-    python fusion_run -inputs ./data/unet.nii.gz,./data/resunet.nii.gz -output ./data/test_simple.nii.gz -classes 0,1,2,4 -method simple 2> /dev/null 
-    if [ $? -eq 0 ]; then
-      exit 0
-    else
-      exit 1
+- script: |
+    python fusion_run -inputs ./data/unet.nii.gz,./data/resunet.nii.gz -output ./data/test_staple.nii.gz -classes 0,1,2,4 -method staple 
+    python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_simple.nii.gz', './data/test_staple.nii.gz'))) else print('pass')"
+    
   displayName: 'Run through all options'
   
-- bash: |
-    python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_staple.nii.gz', './data/test_staple.nii.gz'))) else print('pass')" 2> /dev/null 
-    if [ $? -eq 0 ]; then
-      exit 0
-    else
-      exit 1
-    python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_itkvoting.nii.gz', './data/test_itkvoting.nii.gz'))) else print('pass')" 2> /dev/null 
-    if [ $? -eq 0 ]; then
-      exit 0
-    else
-      exit 1
-    python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_majorityvoting.nii.gz', './data/test_majorityvoting.nii.gz'))) else print('pass')" 2> /dev/null 
-    if [ $? -eq 0 ]; then
-      exit 0
-    else
-      exit 1
-    python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_simple.nii.gz', './data/test_simple.nii.gz'))) else print('pass')" 2> /dev/null 
-    if [ $? -eq 0 ]; then
-      exit 0
-    else
-      exit 1
-  displayName: 'Compare generated results'
+# - bash: |
+#     python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_staple.nii.gz', './data/test_staple.nii.gz'))) else print('pass')" 2> /dev/null 
+#     if [ $? -eq 0 ]; then
+#       exit 0
+#     else
+#       exit 1
+#     python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_itkvoting.nii.gz', './data/test_itkvoting.nii.gz'))) else print('pass')" 2> /dev/null 
+#     if [ $? -eq 0 ]; then
+#       exit 0
+#     else
+#       exit 1
+#     python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_majorityvoting.nii.gz', './data/test_majorityvoting.nii.gz'))) else print('pass')" 2> /dev/null 
+#     if [ $? -eq 0 ]; then
+#       exit 0
+#     else
+#       exit 1
+#     python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_simple.nii.gz', './data/test_simple.nii.gz'))) else print('pass')" 2> /dev/null 
+#     if [ $? -eq 0 ]; then
+#       exit 0
+#     else
+#       exit 1
+#   displayName: 'Compare generated results'
     
